stage_list:
    #- {set: Processing, name: TrackMLFeatureStore, config: prepare_alldata.yaml, batch_config: batch_cpu_default.yaml}
    #- {set: GNN, name: InteractionGNN, config: train_alldata_GNN.yaml, batch_config: batch_gpu_default.yaml, resume_id: }
    #- {set: DNN, name: EdgeClassifier, config: train_alldata_DNN.yaml, batch_config: batch_gpu_default.yaml, resume_id: }
    - {set: Segmenting, name: TrackMLSegment, config: segment_alldata.yaml, batch_config: batch_gpu_default.yaml, resume_id:}
