
common_configs:

  experiment_name: TuneStudy
  artifact_directory: ./ray_tune
  gpus: 1
  clear_directories: True


model_configs:

    # Input/output configuration
    input_dir: /global/homes/a/aakram/cscratch/run/feature_store
    output_dir: /global/homes/a/aakram/cscratch/run/tune_processed
    project: TuneStudy
    edge_cut: 0.5

    # Dataset parameters
    pt_signal_min: 0.
    pt_background_min: 0.
    datatype_names: [[train, val, test]]
    datatype_split: [[8000, 1000, 1000]]

    train_split: [8000, 1000, 1000]
    sorted_events: True

    noise: False
    overwrite: True
    n_workers: 8

    # Model parameters
    spatial_channels: 3
    cell_channels: 0
    hidden: 128
    n_graph_iters: 8
    nb_node_layer: 3
    nb_edge_layer: 3
    emb_channels: 0
    layernorm: True                       # ADAK:: LayerNorm
    batchnorm: True                       # ADAK:: BatchNorm
    directed: True                        # ADAK:: Directed Graph
    batchsize: 128                        # ADAK:: Batch size
    aggregation: sum_max
    hidden_activation: ReLU
    weight: 2
    warmup: 200
    lr: 0.001
    factor: 0.3
    patience: 10
    regime: [pid] # NOTE: [pid] assumes filtering has (not) been performed i.e. variable y_pid (y) exists in Data.
    max_epochs: 10

    # Post-processing
    callbacks:
    
    l1_size: 1000
    l2_size: 2000
    l3_size: 2000
    l4_size: 2000
    l5_size: 1000
    

